FORMAT: 1A
HOST: http://api.gdms.gizwits.com/v1/

# GDMS

GDMS(Gizwits Device Management System) 机智云设备管理系统

# 产品

## 关联产品 [/product/connect]

### 关联产品 [POST]

一个 product_key 只能关联到一个 enterprise_id.

+ Request (application/json)

    + Body

            {
                "enterprise_id": "",
                "enterprise_secret": "",
                "product_key": "",
                "product_secret": ""
            }

+ Response 201 (application/json)

    + Body

            {
            }
