FORMAT: 1A
HOST: http://api.gdms.gizwits.com/v1/

# GDMS

GDMS(Gizwits Device Management System) 机智云设备管理系统

# 错误信息

## 错误信息格式

    {
        "error_code": 5001,
        "error_msg": "body json invalid"
    }

## 错误信息列表

| error_code | error_message     |
|------------|-------------------|
|       5001 | body json invalid |
|       5002 | form invalid      |

# Group 产品

## 关联产品 [/product/connection]

### 创建关联 [POST]

一个 product_key 只能关联到一个 enterprise_id。

+ Request (application/json)

    + Body

            {
                "enterprise_id": "ad7e60f0594247dcba017ba76d2f4275",
                "enterprise_secret": "db2ac98200824181b447b03e4d42f99b",
                "product_key": "c614a62ceb06499984b1bd67422650d7",
                "product_secret": "8f11ee69eb9d4269ba0777ca5e7280f5"
            }

+ Response 201 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
            }

### 取消关联 [DELETE]

产品下存在设备组不允许取消关联。

+ Request (application/json)

    + Body

            {
                "enterprise_id": "ad7e60f0594247dcba017ba76d2f4275",
                "enterprise_secret": "db2ac98200824181b447b03e4d42f99b",
                "product_key": "c614a62ceb06499984b1bd67422650d7",
                "product_secret": "8f11ee69eb9d4269ba0777ca5e7280f5"
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
            }

## 产品信息 [/product/info]

### 获取产品信息 [GET]

+ Request (application/json)

    + Header

        X-GDMS-Product-Token: 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "name": "Good Product"
            }

# Group 授权

## 授权 [/authorize]

### 获取 token [POST]

+ Request (application/json)

    + Body

            {
                "enterprise_id": "ad7e60f0594247dcba017ba76d2f4275",
                "enterprise_secret": "db2ac98200824181b447b03e4d42f99b",
                "product_key": "c614a62ceb06499984b1bd67422650d7",
            }

+ Response 201 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "token": "7cf955ec8b504d6497d83f39ce9b16d2",
                "expired_at": 1372700873
            }

# Group 设备组

## 设备组 [/device_group]

### 创建设备组 [POST]

parent 为可选参数，如果有 parent 表示创建一个子设备组。

+ Request (application/json)

    + Header

        X-GDMS-Product-Token: 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

        {
            "parent": "450efc08ee084a839bbf15d5f9ada9e7"
        }

+ Response 201 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "gid": "06e248b1b3ef4f10a1bfbe78402aa94f"
            }

## 设备组管理 [/device_group/{gid}]

+ Parameters
    + gid (required, string, `06e248b1b3ef4f10a1bfbe78402aa94f`)

### 删除设备组 [DELETE]

删除设备组需要先清空设备组下所有设备。

+ Request (application/json)

    + Header

        X-GDMS-Product-Token: 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
            }

### 更新设备组 [PUT]

一个 MAC 只能属于产品下的某一个分组。

+ 参数
    + ops: 操作，"assign" | "unassign"
    + macs: MAC 列表
    + reassign: 当 ops 为 "assign" 时有效。当 reassgin 为 true，MAC 如果已经在某个设备组下面，会被移动到当前组；当 reassign 为 false，MAC 如果已经在某个设备组下面，则移动失败。

+ Request (application/json)

    + Header

        X-GDMS-Product-Token: 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "ops": "assign",
                "macs": ["5ccc3d9d5205", "ed7a6aaddd5f", "24017a84df87"],
                "reassign": true
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "success": ["5ccc3d9d5205"],
                "failed": ["ed7a6aaddd5f"],
                "unkown": []
            }

+ Request (application/json)

    + Header

        X-GDMS-Product-Token: 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "ops": "unassign",
                "macs": ["ed7a6aaddd5f", "24017a84df87"]
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "success": ["5ccc3d9d5205"],
                "failed": ["ed7a6aaddd5f"],
                "unkown": ["24017a84df87"]
            }
