FORMAT: 1A
HOST: http://enterpriseapi.gizwits.com/

# Enterprise API

# 错误信息

## 错误信息格式

    {
        "error_code": "5001",
        "error_message": "body json invalid",
        "detail": ""
    }

## 错误信息列表

| status_code | error_code | error_message                           |
|-------------|------------|-----------------------------------------|
|         400 |       5001 | body json invalid                       |
|         400 |       5002 | form invalid                            |
|         404 |       5003 | enterprise id not exist                 |
|         400 |       5004 | enterprise secret error                 |
|         400 |       5005 | product secret error                    |
|         400 |       5006 | product exist devicegroups              |
|         404 |       5007 | association not exist                   |
|         400 |       5008 | association existed                     |
|         400 |       5009 | token invalid                           |
|         400 |       5010 | token not match product_key             |
|         400 |       5011 | token has expired                       |
|         400 |       5012 | ip not in white list                    |
|         403 |       5013 | API call rate limit exceed quota        |
|         400 |       5014 | Report has not been generated!          |
|         404 |       5015 | Product key not exist                   |
|         403 |       5201 | device group not belong to this product |
|         404 |       5202 | parent group not exist                  |
|         400 |       5203 | already has one root group              |
|         400 |       5204 | group has subgroup                      |
|         400 |       5205 | group has device item                   |
|         404 |       5206 | group not exist                         |
|         404 |       5301 | device not exist                        |
|         403 |       5302 | device not belong to this product       |
|         400 |       5303 | device not bound                        |
|         400 |       5304 | device is disabled                      |
|         400 |       5401 | attr invalid!                           |
|         400 |       5402 | datapoint data not found!               |
|         400 |       5403 | send command failed!                    |

# 企业响应头部信息

## 返回响应配额头部信息说明

* X-RateLimit-Limit: 60  # 代表企业api可以使用的配额数
* X-RateLimit-Remaining: 56 # 代表调用企业api剩余可用的配额数
* X-RateLimit-Reset: 1372700873 # 配额重置时间戳

# Group 产品

## 关联产品 [/v1/products/{product_key}/association]

### 创建关联 [POST]

一个 product_key 只能关联到一个 enterprise_id。

+ Request (application/json)

    + Body

            {
                "enterprise_id": "ad7e60f0594247dcba017ba76d2f4275",
                "enterprise_secret": "db2ac98200824181b447b03e4d42f99b",
                "product_secret": "8f11ee69eb9d4269ba0777ca5e7280f5"
            }

+ Response 201 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
            }

### 取消关联 [DELETE]

产品下存在设备组不允许取消关联。

+ Request (application/json)

    + Body

            {
                "enterprise_id": "ad7e60f0594247dcba017ba76d2f4275",
                "enterprise_secret": "db2ac98200824181b447b03e4d42f99b",
                "product_secret": "8f11ee69eb9d4269ba0777ca5e7280f5"
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
            }

## 产品关联应用信息 [/v1/products/{product_key}/application{?limit,skip}]

+ Parameters
    + limit (optional, integer, `20`)
    + skip (optional, integer, `1`)

### 获取产品关联的app信息 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "null",
                    "previous": null
                },
                "objects": [{
                        "name": "show1",
                        "appid": "11ddb654c8d2485c846cb6c8f44557a2",
                        "secret": "2da75b8e050349aa841b43efcb24e581"
                    },
                    {
                        "name": "show2",
                        "appid": "11ddb654c8d2485c846cb6c8f44557a2",
                        "secret": "2da75b8e050349aa841b43efcb24e581"
                    }]
            }

## 授权 [/v1/products/{product_key}/access_token]

### 获取 token [POST]

+ Request (application/json)

    + Body

            {
                "enterprise_id": "ad7e60f0594247dcba017ba76d2f4275",
                "enterprise_secret": "db2ac98200824181b447b03e4d42f99b",
                "product_secret": "8f11ee69eb9d4269ba0777ca5e7280f5"
            }

+ Response 201 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "token": "7cf955ec8b504d6497d83f39ce9b16d2",
                "expired_at": 1372700873
            }

## 产品信息 [/v1/products/{product_key}]

### 获取产品信息 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "name": "Good Product",
                "type": "WiFi" | "Bluetooth"
            }

## 产品数据点接口 [/v1/products/{product_key}/datapoint]

### 获取产品数据点 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
    + Body

    {
        "name": "wwaawww",
        "entities": [
            {
                "attrs": [
                    {
                        "display_name": "aa",
                        "name": "aa",
                        "data_type": "bool",
                        "position": {
                            "bit_offset": 0,
                            "len": 1,
                            "unit": "bit",
                            "byte_offset": 0
                        },
                        "type": "status_readonly",
                        "id": 0,
                        "desc": "....."
                    }
                ],
                "display_name": "机智云开发套件",
                "id": 0,
                "name": "entity0"
            }
        ],
        "protocolType": "standard",
        "product_key": "80c466c16d9a4c10abe33b1d4b932d6d",
        "packetVersion": "0x00000004",
        "ui": {
            "object": {
                "version": 4,
                "showEditButton": false
            },
            "sections": [
                {
                    "elements": [
                        {
                            "boolValue": false,
                            "object": {
                                "action": "entity0",
                                "bind": [
                                    "entity0.aa"
                                ],
                                "perm": "N"
                            },
                            "type": "QBooleanElement",
                            "key": "entity0.aa",
                            "title": "aa"
                        }
                    ]
                }
            ]
        }
    }


# Group 企业平台登录（内部）

## 企业平台登录验证 [/enterprises/verfiy]

### 企业平台登录验证 [POST]

仅供 GDMS 连接 SSL 时，SSL 服务器验证 GDMS 时调用。

+ Request (application/json)

    + Body

            {
                "enterprise_id": "ad7e60f0594247dcba017ba76d2f4275",
                "enterprise_secret": "db2ac98200824181b447b03e4d42f99b",
                "ip": "127.0.0.1"
            }

+ Response 200 (application/json)

    + Body

            {
            }


## 企业关联产品列表 [/enterprises/{enterprise_id}/associations{?skip,limit}]

+ Parameters
    + limit (optional, integer, `20`)
    + skip (optional, integer, `0`)

### 获取企业关联产品列表 [GET]

+ Request (application/json)

    + Header

        X-Gizwits-Enterprise-Secret: db2ac98200824181b447b03e4d42f99b

+ Response 200 (application/json)

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/enterprises/{enterprise_id}/associations?skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "product_key": "7cf955ec8b504d6497d83f39ce9b16d2"
                }]
            }

# Group 设备组

## 设备组 [/v1/products/{product_key}/device_groups]

### 创建设备组 [POST]

parent 为可选参数，如果有 parent 表示创建一个子设备组。

一个产品只能有一个根设备组。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

        {
            "parent_gid": "450efc08ee084a839bbf15d5f9ada9e7"
        }

+ Response 201 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "gid": "06e248b1b3ef4f10a1bfbe78402aa94f"
            }

## 设备组管理 [/v1/products/{product_key}/device_groups/{gid}]

+ Parameters
    + gid (required, string, `06e248b1b3ef4f10a1bfbe78402aa94f`)

### 删除设备组 [DELETE]

删除设备组需要先清空设备组下所有设备及子设备组。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
            }

### 更新设备组 [PUT]

一个 MAC 只能属于产品下的某一个分组。

+ 参数
    + action: 操作，"assign" | "unassign"
    + macs: MAC 列表，最多一次上传 1000 个 MAC
    + reassign: 当 action 为 "assign" 时有效。当 reassgin 为 true，MAC 如果已经在某个设备组下面，会被移动到当前组；当 reassign 为 false，MAC 如果已经在某个设备组下面，则移动失败。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "action": "assign",
                "macs": ["5ccc3d9d5205", "ed7a6aaddd5f", "24017a84df87"],
                "reassign": true
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "success": ["5ccc3d9d5205"],
                "failed": ["ed7a6aaddd5f"]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "action": "unassign",
                "macs": ["ed7a6aaddd5f", "24017a84df87"]
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "success": ["5ccc3d9d5205"],
                "failed": ["ed7a6aaddd5f"]
            }

# Group 设备

## 实时报表 [/v1/products/{product_key}/devices/report/rt{?gid}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取实时报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "count": {
                    "activated": 5000,
                    "faulty": 600,
                    "alert": 400
                },
                "location": {
                    "China": {
                        "count": {
                            "activated": 5000,
                            "faulty": 600,
                            "alert": 400
                        },
                        "Guangdong": {
                            "count": {
                                "activated": 5000,
                                "faulty": 600,
                                "alert": 400
                            },
                            "Guangzhou": {
                                "count": {
                                    "activated": 5000,
                                    "faulty": 600,
                                    "alert": 400
                                }
                            }
                        }
                    }
                }
            }

## 设备查询接口 [/v1/products/{product_key}/devices{?mac}]

+ Parameters
    + mac (required, string, `112233445566`) ... mac地址

### 获取设备信息 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "did": "abcada",
                "passcode": "123456"
            }


## 激活报表（大数据） [/v1/products/{product_key}/devices/report/activation{?gid}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取激活报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "total": 5600,
                "activated": 5000,
                "nonactivated": 600,
                "location": {
                    "China": {
                        "count": 1000,
                        "Guangdong": {
                            "count": 500,
                            "Guangzhou": 60
                        }
                    }
                }
            }

## 激活历史报表（大数据） [/v1/products/{product_key}/devices/report/activation/history{?gid,cycle,start,end}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + cycle (required, string, `date`) ... 统计周期，可以为 date|week|month
    + start (required, string, `2015-10-01`) ... 起始周期，为起始日期、起始周或起始月
    + end (required, string, `2015-10-05`) ... 结束周期，为结束日期、结束周或结束月

### 获取激活历史报表 [GET]

日报表最多查询 30 天。
周报表最多查询 53 周。
月报表最多查询 12 月。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "cycle": "date",
                "start": "2015-10-01",
                "end": "2015-10-02",
                "data": [
                    {
                        "date": "2015-10-01",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1000,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "date": "2015-10-02",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1000,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "cycle": "week",
                "start": "2015-13",
                "end": "2015-14",
                "data": [
                    {
                        "week": "2015-13",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1000,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "week": "2015-14",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1000,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "cycle": "month",
                "start": "2015-01",
                "end": "2015-02",
                "data": [
                    {
                        "month": "2015-01",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1000,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "month": "2015-02",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1000,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

## 活跃设备报表（实时） [/v1/products/{product_key}/devices/report/liveness{?gid}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取活跃设备报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "latest_1": 40,
                "latest_7": 100,
                "latest_30": 300,
                "location": {
                    "China": {
                        "latest_1": 40,
                        "latest_7": 100,
                        "latest_30": 300,
                        "Guangdong": {
                            "latest_1": 40,
                            "latest_7": 100,
                            "latest_30": 300,
                            "Guangzhou": {
                                "latest_1": 4s
                                "latest_7": 100,
                                "latest_30": 300,
                            }
                        }
                    }
                }
            }

## 活跃历史报表（大数据） [/v1/products/{product_key}/devices/report/liveness/history{?gid,cycle,start,end}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + cycle (required, string, `date`) ... 统计周期，可以为 date|week|month
    + start (required, string, `2015-10-01`) ... 起始周期，为起始日期、起始周或起始月
    + end (required, string, `2015-10-05`) ... 结束周期，为结束日期、结束周或结束月

### 获取活跃历史报表 [GET]

日报表最多查询 30 天。
周报表最多查询 53 周。
月报表最多查询 12 月。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "cycle": "date",
                "start": "2015-10-01",
                "end": "2015-10-02",
                "data": [
                    {
                        "date": "2015-10-01",
                        "count": 1100,
                        "China": {
                            "count": 1000,
                            "Guangdong": {
                                "count": 300,
                                "Guangzhou": 20
                            }
                        }
                    },
                    {
                        "date": "2015-10-02",
                        "count": 1100,
                        "China": {
                            "count": 1000,
                            "Guangdong": {
                                "count": 300,
                                "Guangzhou": 20
                            }
                        }
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "cycle": "week",
                "start": "2015-13",
                "end": "2015-14",
                "data": [
                    {
                        "week": "2015-13",
                        "count": 1100,
                        "China": {
                            "count": 1000,
                            "Guangdong": {
                                "count": 300,
                                "Guangzhou": 20
                            }
                        }
                    },
                    {
                        "week": "2015-14",
                        "count": 1100,
                        "China": {
                            "count": 1000,
                            "Guangdong": {
                                "count": 300,
                                "Guangzhou": 20
                            }
                        }
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "cycle": "month",
                "start": "2015-01",
                "end": "2015-02",
                "data": [
                    {
                        "month": "2015-01",
                        "count": 1100,
                        "China": {
                            "count": 1000,
                            "Guangdong": {
                                "count": 300,
                                "Guangzhou": 20
                            }
                        }
                    },
                    {
                        "month": "2015-02",
                        "count": 1100,
                        "China": {
                            "count": 1000,
                            "Guangdong": {
                                "count": 300,
                                "Guangzhou": 20
                            }
                        }
                    }
                ]
            }


## 搜索设备（实时） [/v1/products/{product_key}/devices/search{?gid,country,region,city,is_online,is_faulty,is_alert,show_disabled,type,val,liveness_start,limit,skip}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + country (optional, string, `China`)
    + region (optional, string, `Guangdong`)
    + city (optional, string, `Guangzhou`)
    + is_online (optional, integer, `1`) ...  在线为 1，不在线为 0
    + is_faulty (optional, integer, `1`) ... 故障为 1，无故障为 0
    + is_alert (optional, integer, `1`) ... 报警为 1，无报警为 0
    + show_disabled (optional, integer, `1`) ... 显示注销为1，过滤注销为0
    + liveness_start (optional, integer, `1431593561`) ... 最近活跃时间戳
    + type (optional, string, `did`) ... 可以为 did|mac|uid
    + val (optional, string, `gdGn7PzAYf4VrhnVag5x8D`)
    + limit (optional, integer, `20`)
    + skip (optional, integer, `0`)

### 搜索设备 [GET]

mac 地址忽略大小写。
按照设备最近的登陆时间降序排序。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/v1/products/8f11ee69eb9d4269ba0777ca5e7280f5/devices/search?did=gdGn7PzAYf4VrhnVag5x8D&skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "did": "gdGn7PzAYf4VrhnVag5x8D",
                    "mac": "30bd7c6f94fd",
                    "is_online": true,
                    "country": "China",
                    "region": "Guangdong",
                    "city": "Guangzhou",
                    "longitude": 116.30814954222,
                    "latitude": 40.056885091681,
                    "is_faulty": false,
                    "is_alert": false,
                    "latest_online": 1372700873,
                    "created_at": 1372700873
                }]
            }

## 搜索蓝牙设备（实时） [/v1/products/{product_key}/devices/search_bt{?gid,country,region,city,type,val,liveness_start,limit,skip}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + country (optional, string, `China`)
    + region (optional, string, `Guangdong`)
    + city (optional, string, `Guangzhou`)
    + liveness_start (optional, integer, `1431593561`) ... 最近活跃时间戳
    + type (optional, string, `device_sn`) ... 可以为 device_sn|uid
    + val (optional, string, `gdGn7PzAYf4VrhnVag5x8D`)
    + limit (optional, integer, `20`)
    + skip (optional, integer, `0`)

### 搜索蓝牙设备 [GET]

device_sn 地址忽略大小写。

按照设备最近的上报数据时间降序排序。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/v1/products/8f11ee69eb9d4269ba0777ca5e7280f5/devices/search_bt?device_sn=gdGn7PzAYf4VrhnVag5x8D&skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "gid": "xxx",
                    "device_sn": "30bd7c6f94fd",
                    "firmware": "",
                    "country": "China",
                    "region": "Guangdong",
                    "city": "Guangzhou",
                    "longitude": 116.30814954222,
                    "latitude": 40.056885091681,
                    "updated_at": 1372700873,
                    "created_at": 1372700873
                }]
            }


## 设备历史数据（实时） [/v1/products/{product_key}/devices/{did}/data{?start_ts,end_ts,attrs,limit,skip}]

+ Parameters
    + did (required, string, `gdGn7PzAYf4VrhnVag5x8D`)
    + start_ts (optional, integer, `1372700873`)
    + end_ts (optional, integer, `1372701873`)
    + attrs (optional, string, `longitude,latitude`)
    + limit (optional, integer, `20`)
    + skip (optional, integer, `0`)

### 获取设备历史数据 [GET]

按 ts 降序排序。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/v1/products/8f11ee69eb9d4269ba0777ca5e7280f5/devices/gdGn7PzAYf4VrhnVag5x8D/data?start_ts=1372700873&end_ts=1372701873&skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "ts": 1372701873,
                    "attrs": {
                        "longitude": 23.11,
                        "latitude": 112.55
                    }
                }, {
                    "ts": 1372701880,
                    "attrs": {
                        "longitude": 23.11,
                        "latitude": 112.55
                    }
                }]
            }

## 设备上下线记录（实时） [/v1/products/{product_key}/devices/{did}/online{?start_ts,end_ts,limit,skip}]

+ Parameters
    + did (required, string, `gdGn7PzAYf4VrhnVag5x8D`)
    + start_ts (optional, integer, `1372700873`)
    + end_ts (optional, integer, `1372701873`)
    + limit (optional, integer, `20`)
    + skip (optional, integer, `0`)

### 获取设备上下线记录 [GET]

按 ts 降序排序。

设备的心跳统计信息，在设备上下线记录的 Payload 中。

设备上线记录中，payload 记录了设备设备指定的心跳时间间隔（KeepAlive），单位为秒，此 KeepAlive 的值等于设备上传的心跳时间间隔再加上5秒

设备下线记录中，payload 记录了设备的在线时长（duration），以及在线时发送的心跳次数（heartbeat/count），相邻两个心跳的最大间隔时间（heartbeat/max），最小间隔时间（heartbeat/min），平均间隔时间（heartbeat/avg）, 最后一次收到心跳时刻与下线时刻的间隔时间（heartbeat/last），单位为秒

心跳的间隔时间，为m2m收到第n次心跳的时间点（时间戳）与第n-1次心跳的时间点（时间戳）之差，其中n >= 2；当n < 2时，max，min，avg的值固定为0

max，min：计算客户端从接到第一次心跳开始，到最后一次接到心跳为止的时间段内，相邻两个心跳时间差的最大，最小值；

avg：客户端与云端建立链接开始，到最后一次接到心跳为止的时间段，除以心跳次数；

设备下线记录中，payload记录了设备的下线原因（reason），说明各种reason的意义：

mqtt_disconnect：设备主动断开与mqtt的连接

no_heartbeat：m2m在KeepAlive时段内，没有收到设备心跳

tcp_closed：设备主动断开tcp连接

ssl_closed：设备主动断开ssl连接

offline_force：设备重复上线，原有的连接断开

offline_reset：设备注销，断开连接

offline_exception：异常断开连接

offline_sending_density_overflow：客户端发送信息的频率过大，断开链接

offline_sending_data_size_overflow：客户端发送信息的流量过大，断开链接

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/v1/products/8f11ee69eb9d4269ba0777ca5e7280f5/devices/gdGn7PzAYf4VrhnVag5x8D/online?start_ts=1372700873&end_ts=1372701873&skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "timestamp": 1372701873,
                    "type": "dev_online",
                    "payload": ""
                    },{
                    "timestamp": 1372701880,
                    "type": "dev_offline",
                    "payload": "{\"duration\": 0, \"heartbeat\": {\"count\": 4, \"max\": 0, \"avg\": 0, \"last\": 0, \"min\": 0}, \"reason\": \"tcp_closed\"}"
                }]
            }


## 设备通信日志（实时） [/v1/products/{product_key}/devices/{did}/cmd{?start_ts,end_ts,limit,skip}]

+ Parameters
    + did (optional, string, `gdGn7PzAYf4VrhnVag5x8D`)
    + start_ts (optional, integer, `1372700873`)
    + end_ts (optional, integer, `1372701873`)
    + limit (optional, integer, `20`)
    + skip (optional, integer, `0`)

### 获取设备通信日志 [GET]

按 ts 降序排序。
payload 为二进制进行 base64 编码后的结果。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/v1/products/8f11ee69eb9d4269ba0777ca5e7280f5/devices/gdGn7PzAYf4VrhnVag5x8D/cmd?start_ts=1372700873&end_ts=1372701873&skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "timestamp": 1372701873,
                    "type": "dev2app",
                    "payload": "AAAAAwUAAJEEAA=="
                }, {
                    "timestamp": 1372701880,
                    "type": "app2dev",
                    "payload": "AAAAAwUAAJEEAA=="
                }]
            }

## 设备地理位置分布（实时） [/v1/products/{product_key}/devices/locations{?gid,is_online,is_faulty,is_alert}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + is_online (optional, integer, `1`)
    + is_faulty (optional, integer, `0`)
    + is_alert (optional, integer, `1`)

### 获取设备地理位置分布 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "total": 5600,
                "location": {
                    "China": {
                        "count": 1000,
                        "Guangdong": {
                            "count": 500,
                            "Guangzhou": 60
                        }
                    }
                }
            }

## 蓝牙设备地理位置分布（实时） [/v1/products/{product_key}/devices/locations_bt{?gid,liveness_start}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + liveness_start (optional, integer, `1`)

### 获取蓝牙设备地理位置分布 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "total": 5600,
                "location": {
                    "China": {
                        "count": 1000,
                        "Guangdong": {
                            "count": 500,
                            "Guangzhou": 60
                        }
                    }
                }
            }


## 蓝牙设备最近地理位置（实时） [/v1/products/{product_key}/devices/last_locations{?device_sn}]

+ Parameters
    + device_sn (required, string, `aacc0011`)

### 获取蓝牙设备最近地理位置 [GET]

最多返回 10 条最近的经纬度信息，按 time 升序排序。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 10,
                    "limit": 10,
                    "skip": 0,
                    "next": "/v1/products/8f11ee69eb9d4269ba0777ca5e7280f5/devices/last_locations?device_sn=aacc0011&skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "latitude": 12.12,
                    "longitude": 11.11,
                    "time": 1372701873
                }, {
                    "latitude": 12.13,
                    "longitude": 11.13,
                    "time": 1372701883
                }]
            }

## 远程控制设备 [/v1/products/{product_key}/devices/{did}/control]

+ Parameters
    + did (required, string, `gdGn7PzAYf4VrhnVag5x8D`)

### 设置数据点 [POST]

* 只能设置可写类型的数据点
* bool 类型的数据点设置为 true/false
* enum 类型的数据点设置为枚举的字符串
* uint8/uint16/uint32 类型的数据点设置为数字
* binary 类型的数据设置为 hex 类型字符串，如发送一串二进制数据 0x01, 0x02, 0x03, 就写成 "010203"

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "attrs": {
                  "temp": 10
                }
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {}

### 发送原始控制指令 [POST]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "raw": [<byte>, <byte>, ...]
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {}

## 设备绑定功能 [/v1/products/{product_key}/devices/bindings]

### 绑定设备 [POST]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

        {"uid": "uid1",
         "appid": "appid1",
         "dids": ["did1", "did2"]}

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "success": ["abc", "add"],
                "failed": ["adad", "ee"]
            }

### 解除绑定 [DELETE]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

       {"uid": "uid1",
         "appid": "appid1",
         "dids": ["did1", "did2"]}

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "success": ["abc", "add"],
                "failed": ["adad", "ee"]
            }

## 设备概览 [/v1/products/{product_key}/summary]


### 设备概览接口 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body
            {
                "online": 123,  # 设备在线数
                "total": 100, # 累计上线数
                "new": {
                    "today": 55, # 今日新增
                    "yesterday": 10, # 前一天新增
                    "7_day": 100, # 近7天新增
                    "30_day": 1000 # 近30天新增
                },
                "active" {
                    "yesterday": 10, # 昨天活跃
                    "7_day": 100 # 近7天活跃
                }
            }

## 设备活跃详情 [/v1/products/{product_key}/active_devices{?start,end,country,region,city}]

+ Parameters
    + start (optional, string, `2015-08-12`) ... 开始时间
    + end (optional, string, `2015-08-13`) ... 结束时间
    + country (optional, string, `China`) ... 国家
    + region (optional, string, `Guangdong`) ... 省
    + city (optional, string, `Guangzhou`) ... 城市

### 设备活跃详情接口 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2


+ Response 200 (application/json)

    + Header
                X-RateLimit-Limit: 60
                X-RateLimit-Remaining: 56
                X-RateLimit-Reset: 1372700873

    + Body
            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/report/products/8f11ee69eb9d4269ba0777ca5e7280f5/active_devices?skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "report_date": "2016-04-11",
                    "product_key": "ef12ba70c686479f926abebca21210d3",
                    "mac": "accf235cf6ee",
                    "country": "China",
                    "region": "Guangdong",
                    "city": "Guangzhou",
                    "created_at": 1372700873
                }]
            }


## 设备新增详情 [/v1/products/{product_key}/incr_devices{?start,end,country,region,city}]

+ Parameters
    + start (optional, string, `2015-08-12`) ... 开始时间
    + end (optional, string, `2015-08-13`) ... 结束时间
    + country (optional, string, `China`) ... 国家
    + region (optional, string, `Guangdong`) ... 省
    + city (optional, string, `Guangzhou`) ... 城市

### 设备新增详情接口 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2


+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body
            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/report/products/8f11ee69eb9d4269ba0777ca5e7280f5/active_devices?skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "report_date": "2016-04-11",
                    "product_key": "ef12ba70c686479f926abebca21210d3",
                    "mac": "accf235cf6ee",
                    "country": "China",
                    "region": "Guangdong",
                    "city": "Guangzhou",
                    "created_at": 1372700873
                }]
            }


## 活跃周期 [/v1/products/{product_key}/active_cycle]


### 活跃周期查询接口 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body
            {
                "1_week": 30,
                "1_month": 30,
                "3_month": 45,
                "6_month": 60,
                "1_year": 100,
                "active_total": 50
            }


## 连接时长 [/v1/products/{product_key}/connection_duration]

### 连接时长查询接口 [GET]


+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body
            {
                "1_hour": { # 0～1小时
                    "count": 100,
                    "device": 50
                },
                "8_hour": {  # 1～8小时
                    "count": 100,
                    "device": 50
                },
                "1_day": { # 8～24小时
                    "count": 100,
                    "device": 50
                },
                "5_day": {  # 1～5天
                    "count": 100,
                    "device": 50
                },
                "1_month": {  # 5～30天
                    "count": 100,
                    "device": 50
                },
                "1_month_above": { # 30天以上
                    "count": 100,
                    "device": 50
                },
                "online_range": {
                    "0": 22,  # 0-1时段
                    "1": 33   # 1-2时段
                    ....
                }
            }


# Group 用户

## 用户总数报表（实时） [/v1/products/{product_key}/users/report/total{?gid}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取用户总数报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "total": 5600
            }

## 用户新增报表（大数据） [/v1/products/{product_key}/users/report/new{?gid,cycle,start,end}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + cycle (required, string, `date`) ... 统计周期，可以为 date|week|month
    + start (required, string, `2015-10-01`) ... 起始周期，为起始日期、起始周或起始月
    + end (required, string, `2015-10-05`) ... 结束周期，为结束日期、结束周或结束月


### 获取用户新增报表 [GET]

日报表最多查询 30 天。
周报表最多查询 53 周。
月报表最多查询 12 月。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "cycle": "date",
                "start": "2015-10-01",
                "end": "2015-10-02",
                "data": [
                    {
                        "date": "2015-10-01",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "date": "2015-10-02",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "cycle": "week",
                "start": "2015-13",
                "end": "2015-14",
                "data": [
                    {
                        "week": "2015-13",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "week": "2015-14",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "cycle": "month",
                "start": "2015-01",
                "end": "2015-02",
                "data": [
                    {
                        "month": "2015-01",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "month": "2015-02",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

## 蓝牙用户活跃报表（大数据） [/v1/products/{product_key}/users/report/liveness_bt{?gid,cycle,start,end}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + cycle (required, string, `date`) ... 统计周期，可以为 date|week|month
    + start (required, string, `2015-10-01`) ... 起始周期，为起始日期、起始周或起始月
    + end (required, string, `2015-10-05`) ... 结束周期，为结束日期、结束周或结束月


### 蓝牙用户活跃报表 [GET]

日报表最多查询 30 天。
周报表最多查询 53 周。
月报表最多查询 12 月。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "cycle": "date",
                "start": "2015-10-01",
                "end": "2015-10-02",
                "data": [
                    {
                        "date": "2015-10-01",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "date": "2015-10-02",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "cycle": "week",
                "start": "2015-13",
                "end": "2015-14",
                "data": [
                    {
                        "week": "2015-13",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "week": "2015-14",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "cycle": "month",
                "start": "2015-01",
                "end": "2015-02",
                "data": [
                    {
                        "month": "2015-01",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    },
                    {
                        "month": "2015-02",
                        "count": 1100,
                        "location": {
                            "China": {
                                "count": 1100,
                                "Guangdong": {
                                    "count": 300,
                                    "Guangzhou": 20
                                }
                            }
                        }
                    }
                ]
            }

## 搜索用户（实时） [/v1/products/{product_key}/users/search{?type,val,limit,skip}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ...  设备组 ID
    + type (optional, string, `username`) ... 查询条件，为 username|phone|email|did|mac|device_sn
    + val (optional, string, `Bob`) ... 查询条件值
    + limit (optional, integer, `20`) ... 每次返回的条数
    + skip (optional, integer, `0`) ... 每次跳过的条数

### 搜索用户 [GET]

username 为模糊查找；mac 地址忽略大小写；其他精确匹配。
auth_src 可以为 qq, baidu, sina。
只返回和设备具有绑定关系的用户。
按照用户的创建时间升序排序。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/v1/products/8f11ee69eb9d4269ba0777ca5e7280f5/users/search?type=username&val=Bob&skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "uid": "4e31bf18f65041e2922bb1d918ed9299",
                    "username": "Bob",
                    "phone": null,
                    "email": null,
                    "name": "Miracsu",
                    "gender": "M/F/N",
                    "birthday": "2015-08-02",
                    "address": "Guangdong xxxxx",
                    "remark": "remark comment",
                    "created_at": 1372700873,
                    "is_anonymous": false,
                    "auth_src": null
                }]
            }

# Group 故障与报警（大数据）

## 故障设备台数报表 [/v1/products/{product_key}/fault/report/devices{?gid}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取故障设备台数报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "count": {
                    "total": 5600,
                    "resolved": 5000,
                    "unresolved": 600
                },
                "location": {
                    "China": {
                        "count": {
                            "total": 5600,
                            "resolved": 5000,
                            "unresolved": 600
                        },
                        "Guangdong": {
                            "count": {
                                "total": 5600,
                                "resolved": 5000,
                                "unresolved": 600
                            },
                            "Guangzhou": {
                                "count": {
                                    "total": 5600,
                                    "resolved": 5000,
                                    "unresolved": 600
                                }
                            }
                        }
                    }
                }
            }

## 报警设备台数报表 [/v1/products/{product_key}/alert/report/devices{?gid}]

+ Parameters
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取报警设备台数报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "count": {
                    "total": 5600,
                    "resolved": 5000,
                    "unresolved": 600
                },
                "location": {
                    "China": {
                        "count": {
                            "total": 5600,
                            "resolved": 5000,
                            "unresolved": 600
                        },
                        "Guangdong": {
                            "count": {
                                "total": 5600,
                                "resolved": 5000,
                                "unresolved": 600
                            },
                            "Guangzhou": {
                                "count": {
                                    "total": 5600,
                                    "resolved": 5000,
                                    "unresolved": 600
                                }
                            }
                        }
                    }
                }
            }

## 设备绑定功能 [/devices/bindings]

### 绑定设备 [POST]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

        {"uid": "uid1",
         "appid": "did1",
         "dids": ["did1", "did2"]}

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "success": ["abc", "add"],
                "failed": ["adad", "ee"]
            }

### 解除绑定 [DELETE]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

       {"uid": "uid1",
         "appid": "did1",
         "dids": ["did1", "did2"]}

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "success": ["abc", "add"],
                "failed": ["adad", "ee"]
            }

## 故障次数报表 [/v1/products/{product_key}/fault/report/events{?gid}]

### 获取故障次数报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "count": {
                    "total": 5600,
                    "resolved": 5000,
                    "unresolved": 600
                },
                "detail": {
                    "gate": {
                        "total": 5600,
                        "resolved": 5000,
                        "unresolved": 600
                    }
                },
                "location": {
                    "China": {
                        "count": {
                            "total": 5600,
                            "resolved": 5000,
                            "unresolved": 600
                        },
                        "detail": {
                            "gate": {
                                "total": 5600,
                                "resolved": 5000,
                                "unresolved": 600
                            }
                        },
                        "Guangdong": {
                            "count": {
                                "total": 5600,
                                "resolved": 5000,
                                "unresolved": 600
                            },
                            "detail": {
                                "gate": {
                                    "total": 5600,
                                    "resolved": 5000,
                                    "unresolved": 600
                                }
                            },
                            "Guangzhou": {
                                "count": {
                                    "total": 5600,
                                    "resolved": 5000,
                                    "unresolved": 600
                                },
                                "detail": {
                                    "gate": {
                                        "total": 5600,
                                        "resolved": 5000,
                                        "unresolved": 600
                                    }
                                }
                            }
                        }
                    }
                }
            }


## 报警次数报表 [/v1/products/{product_key}/alert/report/events{?gid}]

### 获取报警次数报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

            {
                "gid": null,
                "count": {
                    "total": 5600,
                    "resolved": 5000,
                    "unresolved": 600
                },
                "detail": {
                    "gate": {
                        "total": 5600,
                        "resolved": 5000,
                        "unresolved": 600
                    }
                },
                "location": {
                    "China": {
                        "count": {
                            "total": 5600,
                            "resolved": 5000,
                            "unresolved": 600
                        },
                        "detail": {
                            "gate": {
                                "total": 5600,
                                "resolved": 5000,
                                "unresolved": 600
                            }
                        },
                        "Guangdong": {
                            "count": {
                                "total": 5600,
                                "resolved": 5000,
                                "unresolved": 600
                            },
                            "detail": {
                                "gate": {
                                    "total": 5600,
                                    "resolved": 5000,
                                    "unresolved": 600
                                }
                            },
                            "Guangzhou": {
                                "count": {
                                    "total": 5600,
                                    "resolved": 5000,
                                    "unresolved": 600
                                },
                                "detail": {
                                    "gate": {
                                        "total": 5600,
                                        "resolved": 5000,
                                        "unresolved": 600
                                    }
                                }
                            }
                        }
                    }
                }
            }

## 自定义事件报表（实时） [/v1/products/{product_key}/bt/custom_event{?cycle,start,end,event_id}]

+ Parameters
    + cycle (required, string, `date`) ... 统计周期，可以为 date|week|month
    + start (required, string, `2015-10-01`) ... 起始周期，为起始日期、起始周或起始月
    + end (required, string, `2015-10-05`) ... 结束周期，为结束日期、结束周或结束月
    + event_id (optional, string, `abcdef`, 事件id)

### 获取自定义事件历史报表 [GET]

日报表最多查询 30 天。
周报表最多查询 53 周。
月报表最多查询 12 月。

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "cycle": "date",
                "start": "2015-10-01",
                "end": "2015-10-02",
                "data": [
                    {
                        "date": "2015-10-01",
                        "count": 1100,
                        "events": [
                        {
                            "name": "event1",
                            "count": 30
                        }]
                    },
                    {
                        "date": "2015-10-02",
                        "count": 1100,
                        "events": [
                        {
                            "name": "event1",
                            "count": 30
                        }]
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "cycle": "week",
                "start": "2015-13",
                "end": "2015-14",
                "data": [
                    {
                        "week": "2015-13",
                        "count": 1100,
                        "events": [
                        {
                            "name": "event1",
                            "count": 30
                        }]
                    },
                    {
                        "week": "2015-14",
                        "count": 1100,
                        "events": [
                        {
                            "name": "event1",
                            "count": 30
                        }]
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "cycle": "month",
                "start": "2015-01",
                "end": "2015-02",
                "data": [
                    {
                        "month": "2015-01",
                        "count": 1100,
                        "events": [
                        {
                            "name": "event1",
                            "count": 30
                        }]
                    },
                    {
                        "month": "2015-02",
                        "count": 1100,
                        "events": [
                        {
                            "name": "event1",
                            "count": 30
                        }]
                    }
                ]
            }

# Group 蓝牙OTA

## 蓝牙固件列表 [/product/{product_key}/bt/firmwares{?limit,skip,status}]

+ Parameters
    + limit (optional, integer, `100`)
    + skip (optional, integer, `1`)
    + status (optional, integer, `3`)

### 获取蓝牙固件列表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "null",
                    "previous": null
                },
                "objects": [{
                    "object":{
                        "uuid": "uuid1",
                        "version": "V1",
                        "status": 1,
                        "created_at": 1372700873
                    },
                    "from_objects":[
                        {
                            "uuid": "uuid1",
                            "version": "V2"
                        }
                    ]
                }]
            }


## 创建蓝牙固件 [/product/{product_key}/bt/firmware]

### 创建蓝牙固件 [POST]

+ Request (multipart/form-data)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

        ------WebKitFormBoundaryVyYZxHJDqJZxUuwu
        Content-Disposition: form-data; name="binary"; filename="binary.bin"
        Content-Type: image/gif


        ------WebKitFormBoundaryVyYZxHJDqJZxUuwu
        Content-Disposition: form-data; name="version"

        V1
        ------WebKitFormBoundaryVyYZxHJDqJZxUuwu--

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "uuid":"uuid1",
                "version": "V1",
                "binary": "id",
                "binary_name": "bin_name",
                "status": 1,
                "device_sn": null,
                "created_at": 1372700873
            }

## 蓝牙固件 [/product/{product_key}/bt/firmware/{uuid}]

+ Parameters
    + uuid (required, string, `xxxx`) ... 固件id

### 获取蓝牙固件 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "object":
                {
                    "uuid":"uuid1",
                    "version": "V1",
                    "binary": "id",
                    "binary_name": "bin_name",
                    "status": 1,
                    "device_sn": null,
                    "created_at": 1372700873
                },
                "from_objects":[
                    {
                        "uuid": "uuid1",
                        "version": "V2"
                    }
                ]
            }


### 编辑蓝牙固件 [POST]

* 更新内容包含文件请使用POST

+ Request (multipart/form-data)

    + Header

                Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

                ------WebKitFormBoundaryVyYZxHJDqJZxUuwu
                Content-Disposition: form-data; name="binary"; filename="binary.bin"
                Content-Type: image/gif


                ------WebKitFormBoundaryVyYZxHJDqJZxUuwu
                Content-Disposition: form-data; name="version"

                V1
                ------WebKitFormBoundaryVyYZxHJDqJZxUuwu--

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "uuid":"uuid1",
                "version": "V1",
                "binary": "id",
                "binary_name": "bin_name",
                "status": 1,
                "device_sn": null,
                "created_at": 1372700873
            }


### 更新蓝牙固件 [PUT]

* PUT方法的Request body有如下类型
* device_sn="sn_xxx"; 设定当前固件只能被指定设备验证。（当前固件必须是未验证状态[status=1]才可以成功）
* status=2； 设定当前固件状态2：已验证，3:已发布。（当前固件不能是已发布状态）
* from_uuids=["uuid1","uuid2","uuid3"]; 设定从哪些固件（ids）升级到当前固件并且当前固件为发布。
* from_uuids补充说明如下
* 当前固件必须是已验证状态[status=2]并且
* 从未设定过form_uuids
* 并且所有的form_uuids都是已发布的固件
* 并且from_uuids中不包含当前uuid 才能成功


+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "device_sn": "sn_xxxx"
            }


+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "object":
                {
                    "uuid":"uuid1",
                    "version": "V1",
                    "binary": "id",
                    "binary_name": "bin_name",
                    "status": 1,
                    "device_sn": null,
                    "created_at": 1372700873
                },
                "from_objects":[
                    {
                        "uuid": "uuid1",
                        "version": "V2"
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "status": 1
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "object":
                {
                    "uuid":"uuid1",
                    "version": "V1",
                    "binary": "id",
                    "binary_name": "bin_name",
                    "status": 1,
                    "device_sn": null,
                    "created_at": 1372700873
                },
                "from_objects":[
                    {
                        "uuid": "uuid1",
                        "version": "V2"
                    }
                ]
            }

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

    + Body

            {
                "from_uuids": ["uuid1", "uuid2", "uuid3"]
            }

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "object":
                {
                    "uuid":"uuid1",
                    "version": "V1",
                    "binary": "id",
                    "binary_name": "bin_name",
                    "status": 1,
                    "device_sn": null,
                    "created_at": 1372700873
                },
                "from_objects":[
                    {
                        "uuid": "uuid1",
                        "version": "V2"
                    }
                ]
            }


### 删除蓝牙固件 [DELETE]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 204 (application/json)


## 蓝牙固件下载 [/product/{product_key}/bt/firmware/file{?uuid}]

+ Parameters
    + uuid (required, string, `uuid1`) ... 固件id

### 下载 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2


+ Response 200 (application/octet-stream)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Content-Type: application/octet-stream
            Content-Disposition: attachment; filename=xxxx.bin
            Content-Length: 1000
            Gizwits-Firmware-MD5: SAD8DS
            Gizwits-Firmware-Version: V1

    + Body

        binary

## 升级设备数 [/product/{product_key}/bt/devices/upgraded{?to_uuid}]

+ Parameters
    + to_uuid (required, string, `uuid1`) ... 固件id

### 获取升级设备数 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "totals": 100,
                "upgraded": 50
            }

# Group 聚合数据

## WiFi 聚合数据 [/v1/products/{product_key}/devices/{did}/agg_data{?start_ts,end_ts,attrs,aggregator,unit}]

### Retrieve Aggregated Data [GET]

start_ts 和 end_ts 为带毫秒的整型时间戳。

attrs 只能为数字类型的数据点。

返回的 datetime 格式:

HOURS:  "2015072010"

DAYS:   "20150720"

WEEKS:  "201529"

MONTHS: "201507"

aggregator include [sum,avg,max,min]

unit include [HOURS,DAYS,WEEKS,MONTHS]

+ Parameters
    + did (required, string, `xxx`)
    + start_ts (required, number, `1447837618000`)
    + end_ts (optional, number, `1447837828000`)
    + attrs (required, string, `weight`)
    + aggregator (required, string, `sum`)
    + unit (required, string, `DAYS`)

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873

    + Body

            {
                "query": {
                    "start_ts": 1447837618000,
                    "end_ts": 1447837828000,
                    "attrs": "temp,humi",
                    "aggregator": "sum",
                    "unit": "DAYS",
                    "did": "xxx"
                },
                "data": [{
                    "attrs": {
                        "weight": 50,
                        "fat": 0.2
                    }
                    "datetime": xxx
                },
                {
                    "attrs": {
                        "weight": 50,
                        "fat": 0.2
                    }
                    "datetime": xxx
                }]
            }

## 产品聚合接口 [/v1/products/{product_key}/agg_data{?start_ts,end_ts,aggregator,attrs}]

+ Parameters
    + start_ts (required, number, `1447919887000`) ... 开始日期
    + end_ts (optional, number, `1447919895000`) ... 结束日期
    + aggregator (required, string, `sum`) ... 聚合可以选择sum|avg
    + attrs (required, string, `Cartridge_Life_1,mode`)
    + unit (required, string, `DAYS`)
    + unit_interval (optional, number, `1`) ... 默认为1

### 获取聚合数据 [GET]

* start_ts 和 end_ts 为带毫秒的整型时间戳。
* aggregator 包括[sum, avg, min, max]
* unit 包括[HOURS, DAYS, WEEK, MONTHS]
* attrs只能为数字和枚举的数据点

返回结果的格式：

* type包括[uint, enum],uint代表返回的是数字型的数据点结果，enum代表枚举型的数据点结果

datetime按unit返回的格式是：

* HOURS 返回的日期格式是2015071012, 代表年月日时
* DAYS 返回的日期格式是20150710, 代表年月日
* WEEKS 返回的日期格式是201525, 代表年周
* MONTHS 返回的日期格式是201507，代表年月


枚举值与数据值的聚合区别

* 枚举值是对enum里的聚合value发送次数的累加，如满水：5次，冲洗：6次,是对每个枚举类型值的次数统计
* 数值类型的聚合是对发送值的累加统计

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
    + Body

    {
        "query": {
            "start_ts": "20150813",
            "end_ts": "20150814",
            "attrs": "sum",
            "unit": "DAYS",
            "unit_interval": 1
        },
        "data": [{
            "datetime": "20150813",
            "location": {
                "Guangdong": {
                    "Cartridge_Life_1": {
                        "type": "uint",
                        "value": 33.12
                    },
                    "mode": {
                        "type": "enum",
                        "value": {
                            "满水": 15,
                            "去水": 16
                        }
                    }
                },
                "Shangxi": {
                    "Cartridge_Life_1": {
                        "type": "uint",
                        "value": 35.12
                    },
                    "mode": {
                        "type": "enum",
                        "value": {
                            "满水": 22,
                            "去水": 33
                        }
                    }
                }
            }
        },
        {
            "datetime": "20150814",
            "location": {
                "Guangdong": {
                    "Cartridge_Life_1": {
                        "type": "uint",
                        "value": 33.88
                    },
                    "mode": {
                        "type": "enum",
                        "value": {
                            "满水": 23,
                            "去水": 44
                        }
                    }
                },
                "Shangxi": {
                    "Cartridge_Life_1": {
                        "type": "uint",
                        "value": 37.12
                    },
                    "mode": {
                        "type": "enum",
                        "value": {
                            "满水": 11,
                            "去水": 55
                        }
                    }
                }
            }

        }]
    }

# Group 通用类接口

## 通用报表接口 [/report/products/{product_key}/datas_info{?data_type,gid}]

* data_type:activation 获取激活报表
* data_type:liveness 获取活跃报表
* data_type:total_user 获取总用户数
* data_type:fault_event 故障次数
* data_type:alert_event 报警次数

+ Parameters
    + data_type (required, string, `activation`) ... 报表类型
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取激活报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "total": 5600,
                "activated": 5000,
                "nonactivated": 600,
                "location": {
                    "China": {
                        "count": 1000,
                        "Guangdong": {
                            "count": 500,
                            "Guangzhou": 60
                        }
                    }
                }
            }


## 活跃报表接口 [/report/products/{product_key}/datas_info{?data_type,gid}]

+ Parameters
    + data_type (required, string, `liveness`)
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`)

### 获取活跃报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "latest_1": 40,
                "latest_7": 100,
                "latest_30": 300,
                "location": {
                    "China": {
                        "latest_1": 40,
                        "latest_7": 100,
                        "latest_30": 300,
                        "Guangdong": {
                            "latest_1": 40,
                            "latest_7": 100,
                            "latest_30": 300,
                            "Guangzhou": {
                                "latest_1": 4s
                                "latest_7": 100,
                                "latest_30": 300,
                            }
                        }
                    }
                }
            }


## 用户总数数报表接口 [/report/products/{product_key}/datas_info{?data_type,gid}]

+ Parameters
    + data_type (required, string, `total_user`) ... 报表类型
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取用户总数数报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "total": 5600
            }

## 故障报警次数报表接口 [/report/products/{product_key}/datas_info{?data_type,gid}]

+ Parameters
    + data_type (required, string, `fault_event|alert_event`) ... 报表类型
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID

### 获取故障报警次数报表 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "count": {
                    "total": 5600,
                    "resolved": 5000,
                    "unresolved": 600
                },
                "detail": {
                    "gate": {
                        "total": 5600,
                        "resolved": 5000,
                        "unresolved": 600
                    }
                },
                "location": {
                    "China": {
                        "count": {
                            "total": 5600,
                            "resolved": 5000,
                            "unresolved": 600
                        },
                        "detail": {
                            "gate": {
                                "total": 5600,
                                "resolved": 5000,
                                "unresolved": 600
                            }
                        },
                        "Guangdong": {
                            "count": {
                                "total": 5600,
                                "resolved": 5000,
                                "unresolved": 600
                            },
                            "detail": {
                                "gate": {
                                    "total": 5600,
                                    "resolved": 5000,
                                    "unresolved": 600
                                }
                            },
                            "Guangzhou": {
                                "count": {
                                    "total": 5600,
                                    "resolved": 5000,
                                    "unresolved": 600
                                },
                                "detail": {
                                    "gate": {
                                        "total": 5600,
                                        "resolved": 5000,
                                        "unresolved": 600
                                    }
                                }
                            }
                        }
                    }
                }
            }

## 通用历史报表接口 [/report/products/{product_key}/datas_info{?data_type,gid,cycle,start,end}]

+ Parameters
    + data_type (required, string, `activation_history`) ... 报表类型
    + gid (optional, string, `450efc08ee084a839bbf15d5f9ada9e7`) ... 设备组 ID
    + cycle (required, string, `date`) ... 统计周期，可以为 date|week|month
    + start (required, string, `2015-10-01`) ... 起始周期，为起始日期、起始周或起始月
    + end (required, string, `2015-10-05`) ... 结束周期，为结束日期、结束周或结束月


## 获取通用历史报表 [GET]

* data_type:activation_history 获取激活历史报表
* data_type:liveness_history  活跃历史报表
* data_type:new_user    新增用户数
* data_type:bt_liveness_report  蓝牙活跃报表

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2

+ Response 200 (application/json)

    + Header

            X-RateLimit-Limit: 60
            X-RateLimit-Remaining: 56
            X-RateLimit-Reset: 1372700873
            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body

            {
                "gid": null,
                "total": 5600,
                "activated": 5000,
                "nonactivated": 600,
                "location": {
                    "China": {
                        "count": 1000,
                        "Guangdong": {
                            "count": 500,
                            "Guangzhou": 60
                        }
                    }
                }
            }

## 产品信息列表搜索接口 [/report/products_info?{?product_key}]

### 产品信息列表报表 [GET]

+ Parameters
    + product_key (required, string, `pk1,pk2,pk3`) ... 产品product_key搜索值

+ Response 200 (application/json)

    + Header

            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026f

    + Body

          [{
            "name": "Good Product",
            "type": "WiFi"
            },
            {
              "name": "Good Product",
              "type": "Bluetooth"
              }]

## 设备活跃详情 [/report/products/{product_key}/active_devices{?start,end,country,region,city}]

+ Parameters
    + start (optional, string, `2015-08-12`) ... 开始时间
    + end (optional, string, `2015-08-13`) ... 结束时间
    + country (optional, string, `China`) ... 国家
    + region (optional, string, `Guangdong`) ... 省
    + city (optional, string, `Guangzhou`) ... 城市

### 设备活跃详情接口 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2


+ Response 200 (application/json)

    + Header

            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body
            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/report/products/8f11ee69eb9d4269ba0777ca5e7280f5/active_devices?skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "report_date": "2016-04-11",
                    "product_key": "ef12ba70c686479f926abebca21210d3",
                    "mac": "accf235cf6ee",
                    "country": "China",
                    "region": "Guangdong",
                    "city": "Guangzhou",
                    "created_at": 1372700873
                }]
            }


## 设备新增详情 [/report/products/{product_key}/incr_devices{?start,end,country,region,city}]

+ Parameters
    + start (optional, string, `2015-08-12`) ... 开始时间
    + end (optional, string, `2015-08-13`) ... 结束时间
    + country (optional, string, `China`) ... 国家
    + region (optional, string, `Guangdong`) ... 省
    + city (optional, string, `Guangzhou`) ... 城市
    
### 设备新增详情接口 [GET]

+ Request (application/json)

    + Header

        Authorization: token 7cf955ec8b504d6497d83f39ce9b16d2


+ Response 200 (application/json)

    + Header

            Last-Modified: Fri, 12 May 2015 18:53:33 GMT
            ETag: "5d33c96c1ce649fe84297ce8e026fe66"

    + Body
            {
                "meta": {
                    "total": 100,
                    "limit": 20,
                    "skip": 0,
                    "next": "/report/products/8f11ee69eb9d4269ba0777ca5e7280f5/active_devices?skip=20&limit=20",
                    "previous": null
                },
                "objects": [{
                    "report_date": "2016-04-11",
                    "product_key": "ef12ba70c686479f926abebca21210d3",
                    "mac": "accf235cf6ee",
                    "country": "China",
                    "region": "Guangdong",
                    "city": "Guangzhou",
                    "created_at": 1372700873
                }]
            }
